## This script contains two functions designed to work together to
## compute the inverse of an invertible square matrix, or retrieve
## the inverse from a cache, if available.

## makeCacheMatrix generates a list containing 4 callable functions
## to set or get the input matrix or inverse matrix.  "x" is an 
## invertible square matrix.

makeCacheMatrix <- function(x = matrix()) {
    inv <- NULL
    set <- function(y) {
        x <<- y
        inv <<- NULL
    }
    get <- function() x
    setinverse <- function(solve) inv <<- solve
    getinverse <- function() inv
    list(set = set, get = get,
         setinverse = setinverse,
         getinverse = getinverse)
}

## cacheSolve returns the inverse of a matrix.  If available, the
## inverse is retrieved from cache to avoid recomputation.  "x" 
## is a list object generated by makeCacheMatrix().

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
    inv <- x$getinverse()
    if(!is.null(inv)) {
        message("getting cached data")
        return(inv)
    }
    data <- x$get()
    inv <- solve(data, ...)
    x$setinverse(inv)
    inv
}

## Test lines
# testmatrix<-matrix(c(2,4,3,1,5,7,4,5,6),nrow=3,ncol=3)
# x<-makeCacheMatrix(testmatrix)
# cacheSolve(x)
# solve(testmatrix)

